version: 2.1

executors:
  win32-executor:
    docker:
      - image: cimg/base:edge-20.04
  autotools-executor:
    docker:
      - image: cimg/base:edge-20.04

jobs:

  # will be dropped with autotools removal
  distcheck:
    executor: autotools-executor
    steps:
      - checkout
      - run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y git ninja-build binutils libtool autoconf automake make gcc g++ pkg-config ragel gtk-doc-tools libfontconfig1-dev libfreetype6-dev libglib2.0-dev libcairo2-dev libicu-dev libgraphite2-dev python3 python3-pip cmake
      - run: pip3 install fonttools meson --upgrade
      - run: ./autogen.sh
      - run: make -j32
      - run: make distcheck
      - run: rm harfbuzz-* && make distdir
      - run: cd harfbuzz-* && meson build && ninja -Cbuild test
      - run: cd harfbuzz-* && cmake -Bcmakebuild -H. && cmake --build cmakebuild
      - run: make dist
      - persist_to_workspace:
          root: .
          paths: harfbuzz-*.tar.xz

  publish-dist:
    executor: autotools-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          .ci/publish_release_artifact.sh harfbuzz-$CIRCLE_TAG.tar.xz

  crossbuild-win32:
    executor: win32-executor
    steps:
      - checkout
      - run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y ninja-build binutils meson gcc g++ pkg-config ragel gtk-doc-tools libfreetype6-dev libglib2.0-dev libcairo2-dev libicu-dev libgraphite2-dev python3 python3-pip git g++-mingw-w64-i686 zip
      - run: .ci/build-win32.sh
      - store_artifacts:
          path: harfbuzz-win32.zip
      - persist_to_workspace:
          root: .
          paths: harfbuzz-win32.zip

  publish-win32:
    executor: win32-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          mv harfbuzz-win32{,-$CIRCLE_TAG}.zip
          .ci/publish_release_artifact.sh harfbuzz-win32-$CIRCLE_TAG.zip

workflows:
  version: 2

  build:
    jobs:
      - distcheck # will be dropped with autotools removal
      - publish-dist:
          requires:
            - distcheck
          filters:
            tags:
              only: /^\d+.\d+.\d+$/
            branches:
              ignore: /.*/
      - crossbuild-win32
      - publish-win32:
          requires:
            - crossbuild-win32
          filters:
            tags:
              only: /^\d+.\d+.\d+$/
            branches:
              ignore: /.*/
