version: 2.1

executors:
  win32-executor:
    docker:
      - image: cimg/base:edge-20.04
  autotools-executor:
    docker:
      - image: cimg/base:edge-20.04

jobs:

  # will be dropped with autotools removal
  distcheck:
    executor: autotools-executor
    steps:
      - checkout
      - run: date > harfbuzz-2.7.2.tar.xz
      - persist_to_workspace:
          root: .
          paths: harfbuzz-*.tar.xz

  publish-dist:
    executor: autotools-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          .ci/publish_release_artifact.sh harfbuzz-$CIRCLE_TAG.tar.xz

  crossbuild-win32:
    executor: win32-executor
    steps:
      - checkout
      - run: date > harfbuzz-win32.zip
      - store_artifacts:
          path: harfbuzz-win32.zip
      - persist_to_workspace:
          root: .
          paths: harfbuzz-win32.zip

  publish-win32:
    executor: win32-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          mv harfbuzz-win32{,-$CIRCLE_TAG}.zip
          .ci/publish_release_artifact.sh harfbuzz-win32-$CIRCLE_TAG.zip

workflows:
  version: 2

  build:
    jobs:
      - distcheck # will be dropped with autotools removal
      - publish-dist:
          requires:
            - distcheck
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - crossbuild-win32
      - publish-win32:
          requires:
            - crossbuild-win32
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
